added math helper
artemgusakov/vue-math-game pull request #2
Opened 2021-03-26 19:11 UTC by artemgusakov

2021-03-26 20:04 UTC, sokolgleb requested changes

2021-03-26 20:04 UTC, sokolgleb commented on src/components/Task.vue
> +       this.result = this.math.checkAnswer(task.id, answer)
В this.math.checkAnswer можно передавать сам объект task - тогда тебе не надо его икать по id

2021-03-26 20:04 UTC, sokolgleb commented on src/helpers/math-example-helper.js
> +
Может под Task сделать отдельный класс?
Тогда был класс Task и что-то вроде TaskPool
И у класса Task был бы метод check и его можно было бы проверять прямо в компоненте

2021-04-01 18:40 UTC, artemgusakov commented on src/components/Task.vue
> +        <v-btn depressed color="primary" v-on:click="checkAnswer(task, answer)">
поправил, теперь все из контекста компонента

2021-04-01 18:40 UTC, artemgusakov commented on src/components/Task.vue
> +     checkAnswer: function (task, answer) {
поправил

2021-04-01 18:41 UTC, artemgusakov commented on src/components/Task.vue
> +       this.result = this.math.checkAnswer(task.id, answer)
проверку ответа перенес в класс Task. тут только вызов этого метода

2021-04-01 18:41 UTC, artemgusakov commented on src/helpers/math-example-helper.js
> +
сделано

2021-04-01 20:03 UTC, merged